name: weather_app
description: Just a simple weather app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_typeahead: ^3.1.3

  cupertino_icons: ^1.0.3
  #dart
  redux: ^5.0.0
  redux_epics: ^0.15.0
  built_value: ^8.0.6
  built_collection: ^5.0.0
  freezed_annotation: ^0.14.2
  http: ^0.13.3
  #flutter
  flutter_redux: ^0.8.2
  mocktail: ^0.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

  build_runner: any
  built_value_generator: any
  freezed: any
flutter:
  uses-material-design: true
